// The ladder's order lives here and nowhere else.
//
// A folder name is an identity — the database keys its saved code on it — so
// moving a challenge means moving a line in this file, never a rename. Numbers
// are positions, worked out from this order at load time, so inserting one in
// the middle renumbers everything below it for free.
//
// A folder that is not listed here still shows up, in Unsorted at the bottom.
export const LADDER = [
  {
    name: 'Describing the UI',
    blurb: 'props, JSX, lists — the parts that only read',
    challenges: [
      'greeting-props',
      'destructure-props',
      'children-panel',
      'spread-props',
      'conditional-badge',
      'list-keys',
      'empty-state',
      'derived-total',
      'fallback-values',
      'conditional-classes',
      'pure-render',
      'nested-props',
      'fragment-rows',
      'slot-props',
      'render-prop-list',
    ],
  },
  {
    name: 'State & events',
    blurb: 'events, state, and changing it without mutating',
    challenges: [
      'counter',
      'controlled-form',
      'filter-list',
      'todo-reducer',
      'theme-context',
      'memo-list',
    ],
  },
  {
    name: 'Async & data',
    blurb: 'fetch, loading, errors, races',
    challenges: [
      'fetch-on-mount',
      'loading-flag',
      'error-message',
      'response-not-ok',
      'three-states',
      'refetch-button',
      'fetch-on-id-change',
      'reset-on-id-change',
      'ignore-stale-response',
      'cleanup-on-unmount',
      'fetch-user',
      'parallel-load',
      'sequential-load',
      'settle-partial',
      'retry-once',
      'optimistic-update',
    ],
  },
  {
    name: 'Hooks',
    blurb: 'the ones you rebuild in every project',
    challenges: [
      'use-toggle',
      'use-interval',
      'use-local-storage',
      'use-outside-click',
      'use-pagination',
      'use-undoable',
      'use-ref-focus',
      'use-debounced-value',
      'use-clipboard',
      'use-media-query',
      'use-event-listener',
    ],
  },
  {
    name: 'Components',
    blurb: 'widgets, and the same widget one notch harder',
    challenges: [
      'tabs-compound',
      'modal-portal',
      'toast-system',
      'data-table',
      'wizard',
      'error-boundary',
      'char-counter',
      'star-rating',
      'search-highlight',
      'sortable-list',
      'checkbox-group',
      'countdown',
      'accordion',
      'tag-input',
      'password-strength',
      'load-more',
    ],
  },
  {
    name: 'JS toolbox',
    blurb: 'no React — closures, promises, data',
    challenges: [
      'curry',
      'debounce',
      'throttle',
      'deep-clone',
      'deep-equal',
      'flatten',
      'promise-all',
      'promise-any',
      'promisify',
      'memoize',
      'event-emitter',
      'retry',
      'map-async-limit',
      'get-path',
      'classnames',
      'lru-cache',
      'group-by',
      'dedupe-requests',
      'immutable-set',
      'create-store',
    ],
  },
  {
    name: 'Machine coding',
    blurb: 'interview-sized components',
    challenges: [
      'traffic-light',
      'stopwatch',
      'image-carousel',
      'file-explorer',
      'transfer-list',
      'tic-tac-toe',
      'nested-checkboxes',
      'autocomplete',
      'infinite-scroll',
      'use-query',
      'progress-bars',
      'digital-clock',
      'use-step',
      'memory-game',
      'form-validation',
      'dropdown-menu',
      'poll-widget',
      'use-set',
      'calendar',
      'use-controllable-state',
    ],
  },
  {
    name: 'Hard',
    blurb: 'the ones that need a plan first',
    challenges: [
      'focus-trap',
      'server-table',
      'wordle',
      'selectable-grid',
      'virtual-list',
      'use-store',
      'nested-comments',
      'spreadsheet',
      'imperative-player',
      'use-machine',
      'cascading-select',
      'markdown-lite',
      'tic-tac-toe-n',
      'use-resizable',
      'use-router',
    ],
  },
]
