// The ladder's order lives here and nowhere else.
//
// A folder name is an identity — the database keys its saved code on it — so
// moving a challenge means moving a line in this file, never a rename. Numbers
// are positions, worked out from this order at load time, so inserting one in
// the middle renumbers everything below it for free.
//
// A folder that is not listed here still shows up, in Unsorted at the bottom.
export const LADDER = [
  {
    name: 'Describing the UI',
    blurb: 'props, JSX, lists — the parts that only read',
    challenges: [
      'greeting-props',
      'destructure-props',
      'boolean-props',
      'fallback-values',
      'display-name',
      'children-panel',
      'children-list',
      'conditional-badge',
      'status-chain',
      'escaped-text',
      'style-prop',
      'format-number',
      'array-prop-join',
      'list-keys',
      'index-keys',
      'nested-list',
      'empty-state',
      'no-matches',
      'derived-total',
      'conditional-classes',
      'spread-props',
      'rest-props',
      'nested-props',
      'column-config',
      'pure-render',
      'fragment-rows',
      'slot-props',
      'as-prop',
      'render-prop-list',
      'extract-child',
    ],
  },
  {
    name: 'State & events',
    blurb: 'events, state, and changing it without mutating',
    challenges: [
      'handler-not-call',
      'counter',
      'apply-all-steps',
      'delayed-increment',
      'stop-propagation',
      'submit-prevent-default',
      'controlled-form',
      'fields-by-name',
      'edit-draft',
      'update-one-field',
      'nested-object-update',
      'quantity-by-id',
      'add-to-list',
      'remove-by-id',
      'update-one-item',
      'insert-at',
      'move-item',
      'filter-list',
      'todo-reducer',
      'theme-context',
      'memo-list',
    ],
  },
  {
    name: 'Async & data',
    blurb: 'fetch, loading, errors, races',
    challenges: [
      'fetch-on-mount',
      'loading-flag',
      'error-message',
      'response-not-ok',
      'three-states',
      'refetch-button',
      'fetch-on-id-change',
      'reset-on-id-change',
      'ignore-stale-response',
      'cleanup-on-unmount',
      'fetch-user',
      'parallel-load',
      'sequential-load',
      'settle-partial',
      'retry-once',
      'retry-with-backoff',
      'give-up-on-timeout',
      'poll-on-tick',
      'poll-until-done',
      'debounced-search',
      'cursor-paging',
      'in-flight-guard',
      'filter-resets-page',
      'cache-by-id',
      'share-in-flight',
      'stale-while-revalidate',
      'optimistic-update',
      'revert-to-confirmed',
      'rollback-one-edit',
      'refetch-after-save',
    ],
  },
  {
    name: 'Hooks',
    blurb: 'the ones you rebuild in every project',
    challenges: [
      'use-counter',
      'use-boolean',
      'use-toggle',
      'use-toggle-with-reset',
      'use-default',
      'use-previous',
      'use-is-first-render',
      'use-force-update',
      'use-array',
      'use-map',
      'use-cycle',
      'use-state-with-history',
      'use-latest',
      'use-mounted-ref',
      'use-ref-focus',
      'use-event-listener',
      'use-media-query',
      'use-clipboard',
      'use-outside-click',
      'use-timeout',
      'use-interval',
      'use-countdown',
      'use-debounced-value',
      'use-local-storage',
      'use-pagination',
      'use-undoable',
    ],
  },
  {
    name: 'Components',
    blurb: 'widgets, and the same widget one notch harder',
    challenges: [
      'breadcrumbs',
      'segmented-control',
      'switch-toggle',
      'dismissible-alert',
      'avatar-stack',
      'truncate-text',
      'char-counter',
      'star-rating',
      'star-rating-keyboard',
      'countdown',
      'copy-button',
      'tooltip',
      'search-highlight',
      'accordion',
      'accordion-keep-mounted',
      'accordion-keyboard',
      'tabs-compound',
      'tabs-roving-focus',
      'checkbox-group',
      'tag-input',
      'password-strength',
      'pagination-control',
      'load-more',
      'sortable-list',
      'data-table',
      'data-table-select-rows',
      'modal-portal',
      'modal-focus-return',
      'toast-system',
      'wizard',
      'error-boundary',
    ],
  },
  {
    name: 'JS toolbox',
    blurb: 'no React — closures, promises, data',
    challenges: [
      'range',
      'chunk',
      'partition',
      'unique-by',
      'zip-unzip',
      'group-by',
      'count-by',
      'sort-by',
      'pick-omit',
      'camel-keys',
      'flatten',
      'deep-clone',
      'deep-equal',
      'deep-merge',
      'immutable-set',
      'get-path',
      'query-string',
      'classnames',
      'once',
      'compose-pipe',
      'curry',
      'memoize',
      'intersection-difference',
      'promisify',
      'promise-all',
      'promise-all-settled',
      'promise-any',
      'debounce',
      'throttle',
      'retry',
      'map-async-limit',
      'dedupe-requests',
      'event-emitter',
      'lru-cache',
      'create-store',
    ],
  },
  {
    name: 'Machine coding',
    blurb: 'interview-sized components',
    challenges: [
      'traffic-light',
      'stopwatch',
      'image-carousel',
      'file-explorer',
      'transfer-list',
      'tic-tac-toe',
      'nested-checkboxes',
      'autocomplete',
      'infinite-scroll',
      'use-query',
      'progress-bars',
      'digital-clock',
      'use-step',
      'memory-game',
      'form-validation',
      'dropdown-menu',
      'poll-widget',
      'use-set',
      'calendar',
      'use-controllable-state',
    ],
  },
  {
    name: 'Hard',
    blurb: 'the ones that need a plan first',
    challenges: [
      'focus-trap',
      'server-table',
      'wordle',
      'selectable-grid',
      'virtual-list',
      'use-store',
      'nested-comments',
      'spreadsheet',
      'imperative-player',
      'use-machine',
      'cascading-select',
      'markdown-lite',
      'tic-tac-toe-n',
      'use-resizable',
      'use-router',
    ],
  },
]
